import os
import time
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.progress import Progress, SpinnerColumn, TextColumn
import requests
import gspread
from google.oauth2.service_account import Credentials

console = Console()

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def validate_shopify(shop_url, token, version):
    """Validates Shopify credentials by making a small API call"""
    if not shop_url.startswith('https://'):
        shop_url = f'https://{shop_url}'
    
    # Clean trailing slashes
    shop_url = shop_url.rstrip('/')
    
    url = f"{shop_url}/admin/api/{version}/shop.json"
    headers = {
        "X-Shopify-Access-Token": token,
        "Content-Type": "application/json"
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            shop_name = response.json().get('shop', {}).get('name')
            return True, f"Successfully connected to store: [bold green]{shop_name}[/bold green]"
        elif response.status_code == 401:
            return False, "Authentication failed. Check your Access Token."
        else:
            return False, f"Failed with Status Code: {response.status_code}"
    except Exception as e:
        return False, f"Connection Error: {str(e)}"

def validate_sheets(cred_path, sheet_name):
    """Validates Google Sheets credentials"""
    if not os.path.exists(cred_path):
        return False, f"File not found: {cred_path}"
    
    try:
        scopes = ['https://www.googleapis.com/auth/spreadsheets']
        creds = Credentials.from_service_account_file(cred_path, scopes=scopes)
        client = gspread.authorize(creds)
        
        # Try to open sheet
        base_sheet = client.open(sheet_name)
        return True, f"Successfully found sheet: [bold green]{base_sheet.title}[/bold green]"
    except gspread.exceptions.SpreadsheetNotFound:
        return False, "Spreadsheet not found. Check the name and ensure you've shared it with the Service Account email."
    except Exception as e:
        return False, f"Error: {str(e)}"

def run_wizard():
    clear_screen()
    console.print(Panel.fit("[bold blue]AliExpress -> Shopify Automation Setup[/bold blue]", subtitle="Configure your environment"))
    
    console.print("\n[yellow]Welcome! This wizard will help you connect your accounts.[/yellow]\n")
    
    # --- Shopify Setup ---
    console.rule("[bold]Step 1: Shopify Configuration[/bold]")
    
    while True:
        shop_url = Prompt.ask("Enter your Shopify Shop URL (e.g. [cyan]mystore.myshopify.com[/cyan])")
        access_token = Prompt.ask("Enter your Admin API Access Token", password=True)
        api_version = Prompt.ask("Enter API Version", default="2024-01")
        
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as progress:
            progress.add_task(description="Validating Shopify connection...", total=None)
            is_valid, message = validate_shopify(shop_url, access_token, api_version)
            
        if is_valid:
            console.print(f"✅ {message}")
            break
        else:
            console.print(f"❌ {message}")
            if not Confirm.ask("Try again?"):
                return

    # --- Google Sheets Setup ---
    console.print("\n")
    console.rule("[bold]Step 2: Google Sheets Configuration[/bold]")
    
    while True:
        cred_path = Prompt.ask("Enter path to your Google Service Account JSON file", default="credentials.json")
        sheet_name = Prompt.ask("Enter the exact Name of your Google Sheet")
        
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as progress:
            progress.add_task(description="Validating Google connection...", total=None)
            is_valid, message = validate_sheets(cred_path, sheet_name)
            
        if is_valid:
            console.print(f"✅ {message}")
            break
        else:
            console.print(f"❌ {message}")
            if not Confirm.ask("Try again?"):
                return

    # --- Save Configuration ---
    console.print("\n")
    console.rule("[bold]Step 3: Saving Configuration[/bold]")
    
    env_content = f"""# Auto-generated by Setup Wizard
SHOPIFY_SHOP_URL={shop_url}
SHOPIFY_ACCESS_TOKEN={access_token}
SHOPIFY_API_VERSION={api_version}

GOOGLE_SHEETS_CREDENTIALS_FILE={cred_path}
GOOGLE_SHEET_NAME={sheet_name}
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        console.print("✅ [bold green]Configuration saved to .env file![/bold green]")
        
        console.print("\n[bold]Setup Complete![/bold]")
        console.print("You can now run the automation script normally.")
        
    except Exception as e:
        console.print(f"❌ Error saving file: {e}")

if __name__ == "__main__":
    try:
        run_wizard()
    except KeyboardInterrupt:
        console.print("\n[red]Setup cancelled by user.[/red]")
